spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/card_db?currentSchema=card_test
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:sa}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: card_test
    show-sql: false
